version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: saykotoba-backend:latest
    container_name: backend
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - /home/${USER}/saykotoba-backend/config/env/.env.prod:/app/config/env/.env.prod:ro
    env_file:
      - /home/${USER}/saykotoba-backend/config/env/.env.prod
    networks:
      - saykotoba-network

networks:
  saykotoba-network:
    driver: bridge

volumes:
  db-data:
