version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/saykotoba-backend:latest
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: always
    volumes:
      - /home/${USER}/saykotoba-backend/config:/app/config:ro
    env_file:
      - /home/${USER}/saykotoba-backend/config/env/.env.prod
    networks:
      - saykotoba-network

networks:
  saykotoba-network:
    driver: bridge

volumes:
  db-data:
