version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: saykotoba-backend:latest
    container_name: backend
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - /config/env/.env.prod
    environment:
      - NODE_ENV=production
      # AWS 관련 설정
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      # RDS PostgreSQL 설정
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443' # HTTPS를 위한 포트 추가
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro # SSL 인증서 경로
      - ./certbot/www:/var/www/certbot:ro # SSL 인증 챌린지용
    depends_on:
      - backend

networks:
  saykotoba-network:
    driver: bridge

volumes:
  db-data:
