services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    networks:
      - saykotoba-network
    command: ['nginx', '-g', 'daemon off;']

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: ['sh', '-c', 'while true; do certbot renew; sleep 12h; done']

  api-blue:
    image: ${DOCKERHUB_USERNAME}/saykotoba-backend:latest
    container_name: api-blue
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: always
    volumes:
      - /home/${USER}/saykotoba-backend/config:/app/config:ro
    env_file:
      - /home/${USER}/saykotoba-backend/config/env/.env.prod
    networks:
      - saykotoba-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5G'
      update_config:
        order: stop-first

  api-green:
    image: ${DOCKERHUB_USERNAME}/saykotoba-backend:latest
    container_name: api-green
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: always
    volumes:
      - /home/${USER}/saykotoba-backend/config:/app/config:ro
    env_file:
      - /home/${USER}/saykotoba-backend/config/env/.env.prod
    networks:
      - saykotoba-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5G'
      update_config:
        order: stop-first

  api-dev:
    image: ${DOCKERHUB_USERNAME}/saykotoba-backend:dev
    container_name: api-dev
    environment:
      - NODE_ENV=development
      - PORT=8080
    restart: always
    volumes:
      - /home/${USER}/saykotoba-backend/config:/app/config:ro
    env_file:
      - /home/${USER}/saykotoba-backend/config/env/.env.dev
    networks:
      - saykotoba-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '512M'
      update_config:
        order: stop-first

networks:
  saykotoba-network:
    driver: bridge
