export enum DIFFICULTY_MAP {
  BEGINNER,
  ELEMENTARY,
  INTERMEDIATE,
  UPPER_INTERMEDIATE,
  ADVANCED,
  CHALLENGE,
}

export const SCORE_THRESHOLD = {
  PASS: 90,
};

export const EXP_PER_CONVERSATION = {
  BEGINNER: 10,
  ELEMENTARY: 25,
  INTERMEDIATE: 50,
  UPPER_INTERMEDIATE: 100,
  ADVANCED: 200,
  CHALLENGE: 500,
};
