export enum DIFFICULTY_MAP {
  BEGINNER,
  ELEMENTARY,
  INTERMEDIATE,
  UPPER_INTERMEDIATE,
  ADVANCED,
  CHALLENGE,
}

export const SCORE_THRESHOLD = {
  PASS: 80,
};

export const EXP_PER_CONVERSATION: Record<DIFFICULTY_MAP, number> = {
  [DIFFICULTY_MAP.BEGINNER]: 10,
  [DIFFICULTY_MAP.ELEMENTARY]: 25,
  [DIFFICULTY_MAP.INTERMEDIATE]: 50,
  [DIFFICULTY_MAP.UPPER_INTERMEDIATE]: 100,
  [DIFFICULTY_MAP.ADVANCED]: 200,
  [DIFFICULTY_MAP.CHALLENGE]: 500,
};

export enum CONVERSATION_GROUP_TYPE {
  LECTURE = 'LECTURE',
  CUSTOM = 'CUSTOM',
}

export enum CONVERSATION_TYPE {
  CUSTOM = 'CUSTOM',
  LECTURE = 'LECTURE',
}

export const HINT_COUNT = {
  [DIFFICULTY_MAP.BEGINNER]: 5,
  [DIFFICULTY_MAP.ELEMENTARY]: 4,
  [DIFFICULTY_MAP.INTERMEDIATE]: 3,
  [DIFFICULTY_MAP.UPPER_INTERMEDIATE]: 2,
  [DIFFICULTY_MAP.ADVANCED]: 1,
  [DIFFICULTY_MAP.CHALLENGE]: 0,
};
