export enum DIFFICULTY_MAP {
  BEGINNER,
  ELEMENTARY,
  INTERMEDIATE,
  UPPER_INTERMEDIATE,
  ADVANCED,
  CHALLENGE,
}

export const SCORE_THRESHOLD = {
  PASS: 90,
};

export const EXP_PER_CONVERSATION: Record<DIFFICULTY_MAP, number> = {
  [DIFFICULTY_MAP.BEGINNER]: 10,
  [DIFFICULTY_MAP.ELEMENTARY]: 25,
  [DIFFICULTY_MAP.INTERMEDIATE]: 50,
  [DIFFICULTY_MAP.UPPER_INTERMEDIATE]: 100,
  [DIFFICULTY_MAP.ADVANCED]: 200,
  [DIFFICULTY_MAP.CHALLENGE]: 500,
};
