export const AuthErrorMessage = {
  UserNotFound: 'User not found',
  PasswordNotMatch: 'Password not match',
  RefreshTokenSaveFailed: 'Refresh token save failed',
  InvalidRefreshToken: 'Invalid refresh token',
  ExpiredRefreshToken: 'Expired refresh token',
  RefreshTokenFailed: 'Refresh token failed',
  LogoutFailed: 'Logout failed',
  EmailAlreadyExists: 'Email already exists',
  PasswordHashFailed: 'Password hash failed',
  TokenGenerateFailed: 'Token generate failed',
  TokenCleanupFailed: 'Token cleanup failed',
  GoogleOAuthFailed: 'Google OAuth failed',
  AppleOAuthFailed: 'Apple OAuth failed',
  GoogleIdTokenVerifyFailed: 'Google ID token verify failed',
  AppleIdTokenVerifyFailed: 'Apple ID token verify failed',
};
